fix: 临时修复svg缩略图损坏
MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes pull request #202
Opened 2023-05-14 15:34 UTC by BearBin1215

大概能有更优雅的方法，不过这个目前测试了挺多天没出现过问题，能用就不改了。
理论上应该只有直接使用`<img />`标签然后还带`srcset`属性并且图片url内有`thumb/`或`.svg/`才会出现问题。

2023-05-14 16:12 UTC, dragon-fish requested changes
Site wide glitches fixes not applicable here

2023-05-14 16:18 UTC, BearBin1215 commented
> Site wide glitches fixes not applicable here

如果不是放置了一个月以上没修复，也不至于会来这里通过js做临时措施

2023-05-14 16:22 UTC, dragon-fish commented
> > Site wide glitches fixes not applicable here
> 
> 如果不是放置了一个月以上没修复，也不至于会来这里通过js做临时措施

你不能引入一个 unexpected behavior 来修复 unexpected error，你有点太极端了

2023-05-14 16:28 UTC, BearBin1215 commented
> 

我承认自己有点急，这个月在站内外不止一次见到反馈这个问题的了。本身这个问题已经影响到相当大量的页面，我不觉得使用临时措施是什么错误的做法，无非修好之后再roll回去就是了。退一步讲，用svg而非png缩略图也有助于提高图片清晰度。
或者能否提供一下大概什么时候能修好？一直把问题留着也不好吧。

2023-05-14 18:25 UTC, gui-ying233 commented
[WAF娘](https://zh.moegirl.org.cn/WAF%E5%A8%98)的大萌字无法加载，且是否判断属于img.moegirl.org.cn会更好。

2023-05-15 02:34 UTC, AnnAngela commented on src/gadgets/site-js/MediaWiki:Gadget-site-js.js
> +    // 临时修复svg缩略图损坏
@BearBin1215 看一下这样行不

2023-05-15 02:35 UTC, AnnAngela commented on src/gadgets/site-js/MediaWiki:Gadget-site-js.js
> +    }
@BearBin1215 看一下这样行不

2023-05-15 03:00 UTC, BearBin1215 commented on src/gadgets/site-js/MediaWiki:Gadget-site-js.js
> +    }
我在写这段代码的时候和鬼影测试了很多，其中一个测试场景就是把`<img>`的data-lazy-`等属性给到非懒加载相关属性里面、然后再把这些`data-lazy-`全部去掉，结果它还是懒加载了。所以我推测懒加载是在文档加载的时候就把相关data都读取完了，才有了最后一行的`$(this).replaceWith($(this).clone());`，单单删懒加载相关属性是没用的。  
不过昨晚小鱼找我私聊了，他会去找e哥解决问题。

2023-05-15 03:41 UTC, AnnAngela commented on src/gadgets/site-js/MediaWiki:Gadget-site-js.js
> +    }
@BearBin1215 加了个`cloneNode(deep)`

2023-05-15 03:54 UTC, gui-ying233 commented on src/gadgets/site-js/MediaWiki:Gadget-site-js.js
> +    }
> [WAF娘](https://zh.moegirl.org.cn/WAF%E5%A8%98)的大萌字无法加载，且是否判断属于img.moegirl.org.cn会更好。

这个问题又回来了（

2023-05-15 03:59 UTC, gui-ying233 commented on src/gadgets/site-js/MediaWiki:Gadget-site-js.js
> +    }
> @BearBin1215 加了个`cloneNode(deep)`

img 的话不用 deep 吧？

2023-05-15 04:36 UTC, gui-ying233 reviewed
> [WAF娘](https://zh.moegirl.org.cn/WAF%E5%A8%98)的大萌字无法加载，且是否判断属于img.moegirl.org.cn会更好。

这个问题又回来了（

2023-05-15 06:44 UTC, AnnAngela commented
经讨论，临时以 8df56dcc68428e9809fd42259363a74fbfbc8721 引入的独立小工具实现，暂不对所有用户默认开启

2023-05-15 06:44 UTC, closed without merging