feat: + copyUserList
MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes pull request #351
Opened 2023-10-28 13:36 UTC by lovelyCARDINAL

2023-10-28 13:54 UTC, AnnAngela requested changes

2023-10-28 13:54 UTC, AnnAngela commented on src/groups/zh/checkuser/MediaWiki:Group-checkuser.js
> +            const nextSection = h3s[nextIndex];
```suggestion
        h3s.slice(0, -1).forEach((section, index) => {
            const nextSection = h3s[index + 1];
```

2023-10-28 13:54 UTC, AnnAngela commented on src/groups/zh/checkuser/MediaWiki:Group-checkuser.js
> +            })();
```suggestion
            const userlist = 
            for (let ele = section.nextElementSibling; ele && ele !== nextSection; ele = ele.nextElementSibling) {
                const elements = ele.querySelectorAll("li > a");
                const usernames = Array.from(elements)
                    .map((a) => a.textContent.trim())
                    .filter((text) => text.match(/^user:/i));
                userlist.push(...usernames);
            }
```

2023-10-28 13:54 UTC, AnnAngela commented on src/groups/zh/checkuser/MediaWiki:Group-checkuser.js
> +            });
```suggestion
            let lastClicked = -1;
            $copyButton.on("click", () => {
                navigator.clipboard.writeText(userlist.join("\n"));
                $copyButton.text("复制列表成功");
                lastClicked = Date.now() + 2000 - 2;
                setTimeout(() => {
                    if (Date.now() > lastClicked) {
                        $copyButton.text("复制用户列表");
                    }
                }, 2000);
            });
```

2023-10-28 14:00 UTC, lovelyCARDINAL commented on src/groups/zh/checkuser/MediaWiki:Group-checkuser.js
> +            });
话说这个更改有啥用（？
连续点击复制的是同一个内容问题不大？

2023-10-29 00:48 UTC, AnnAngela commented on src/groups/zh/checkuser/MediaWiki:Group-checkuser.js
> +            });
只是想弄优雅点，其实没啥大差别

2023-10-29 05:40 UTC, merged

2023-10-29 07:08 UTC, AnnAngela approved these changes