fix(Gadget/autoconfirmedUserPing): :bug: Fixed #157 (task 2)
MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes pull request #450
Opened 2024-04-04 06:31 UTC by gui-ying233

改分支名导致 #438 关了并似乎无法重新打开（

2024-04-04 09:42 UTC, lovelyCARDINAL commented on src/gadgets/autoconfirmedUserPing/MediaWiki:Gadget-autoconfirmedUserPing.js
> +                const blockIn60days = async (u) => {
建议query+usercontribs和query+logevents合并成一个请求处理
可以减少一半的API请求

2024-04-05 03:42 UTC, lovelyCARDINAL approved these changes

2024-04-05 11:37 UTC, lovelyCARDINAL requested changes

2024-04-05 11:37 UTC, lovelyCARDINAL commented on src/gadgets/autoconfirmedUserPing/MediaWiki:Gadget-autoconfirmedUserPing.js
> +                    pcexcludegroup: "bot|bureaucrat|sysop|patroller|staff",
感觉不对，L142不需要
1、上面已经获取了模块:UserGroup/data和bot用户组成员用来排除
2、这里至少不应该排除patroller，因为存在实习期的patroller

2024-04-06 18:50 UTC, gui-ying233 commented on src/gadgets/autoconfirmedUserPing/MediaWiki:Gadget-autoconfirmedUserPing.js
> +                    pcexcludegroup: "bot|bureaucrat|sysop|patroller|staff",
删了patroller

2024-04-06 18:51 UTC, lovelyCARDINAL commented on src/gadgets/autoconfirmedUserPing/MediaWiki:Gadget-autoconfirmedUserPing.js
> +                    pcexcludegroup: "bot|bureaucrat|sysop|patroller|staff",
所以这里为啥要处理用户组两次
<!-- BOT-MESSAGE-FOOTER -->

2024-04-06 19:02 UTC, gui-ying233 commented on src/gadgets/autoconfirmedUserPing/MediaWiki:Gadget-autoconfirmedUserPing.js
> +                    pcexcludegroup: "bot|bureaucrat|sysop|patroller|staff",
减少返回的数量以减少可能的pccontinue以及加快速度（虽然我不知道为什么之前觉得500的数量还不够加了个while

感觉可以把while直接删掉

2024-04-06 19:05 UTC, lovelyCARDINAL commented on src/gadgets/autoconfirmedUserPing/MediaWiki:Gadget-autoconfirmedUserPing.js
> +                    pcexcludegroup: "bot|bureaucrat|sysop|patroller|staff",
那前面用户组那边是不是可以不请求bot用户组
或者直接前面只要patroller？
<!-- BOT-MESSAGE-FOOTER -->

2024-04-06 19:06 UTC, gui-ying233 commented on src/gadgets/autoconfirmedUserPing/MediaWiki:Gadget-autoconfirmedUserPing.js
> +                    pcexcludegroup: "bot|bureaucrat|sysop|patroller|staff",
前面那直接获取的完整页面，没啥区别，不过确实可以（

2024-04-06 19:06 UTC, gui-ying233 commented on src/gadgets/autoconfirmedUserPing/MediaWiki:Gadget-autoconfirmedUserPing.js
> +                    pcexcludegroup: "bot|bureaucrat|sysop|patroller|staff",
如果删掉pcexcludegroup的话可以用pcrights把L158的自确检查放过来

2024-04-06 19:10 UTC, lovelyCARDINAL commented on src/gadgets/autoconfirmedUserPing/MediaWiki:Gadget-autoconfirmedUserPing.js
> +                    pcexcludegroup: "bot|bureaucrat|sysop|patroller|staff",
我没意见 只是觉得获取bot用户组会耗时 问题不大
<!-- BOT-MESSAGE-FOOTER -->

2024-04-06 19:11 UTC, lovelyCARDINAL approved these changes

2024-04-08 08:13 UTC, lovelyCARDINAL commented
什么时候可以合

2024-04-08 08:23 UTC, gui-ying233 commented
> 什么时候可以合

我想等一次提案进行测试（（
先合了也可以（

2024-04-08 10:13 UTC, merged