feat(Gadget-libOOUIDialog): Force `required`
MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes pull request #5
Opened 2022-09-10 13:21 UTC by AnnAngela

乐然帮我看看有啥问题没有~

2022-09-11 09:31 UTC, leranjun requested changes

2022-09-11 09:31 UTC, leranjun commented on src/gadgets/libOOUIDialog/MediaWiki:Gadget-libOOUIDialog.js
> +                if (required && !result) {
是不是需要`result !== null`？如果用户选择取消了的话`result`是`null`会不会死循环

2022-09-11 09:34 UTC, leranjun commented on src/gadgets/libOOUIDialog/MediaWiki:Gadget-libOOUIDialog.js
> +                if (required && !result) {
以及为啥不用内置的[`getValidity`](https://doc.wikimedia.org/oojs-ui/master/js/#!/api/OO.ui.TextInputWidget-method-getValidity)

就 除了required以外会不会有pattern限制

2022-09-11 09:39 UTC, leranjun commented on src/gadgets/libOOUIDialog/MediaWiki:Gadget-libOOUIDialog.js
> +                if (required && !result) {
或者换个思路 加个`validate`参数对应OOUI的[`validate`](https://doc.wikimedia.org/oojs-ui/master/js/#!/api/OO.ui.TextInputWidget-cfg-validate) 然后把required参数设置成`validate: "non-empty"`的语法糖？

2022-09-11 09:45 UTC, leranjun requested changes

2022-09-11 09:45 UTC, leranjun commented on src/gadgets/libOOUIDialog/MediaWiki:Gadget-libOOUIDialog.js
> +                    base.textInput.indicator = "required";
这里是不是可以换成[`setIndicator`](https://doc.wikimedia.org/oojs-ui/master/js/#!/api/OO.ui.mixin.IndicatorElement-method-setIndicator)

2022-09-11 09:45 UTC, leranjun commented on src/gadgets/libOOUIDialog/MediaWiki:Gadget-libOOUIDialog.js
> +                base.textInput.required = true;
`textInput`没有required这个属性吧

2022-09-11 09:45 UTC, leranjun commented on src/gadgets/libOOUIDialog/MediaWiki:Gadget-libOOUIDialog.js
> +                    base.textInput.validate = "not-empty";
同理可以换成[`setValidation`](https://doc.wikimedia.org/oojs-ui/master/js/#!/api/OO.ui.TextInputWidget-method-setValidation)？

2022-09-11 09:57 UTC, AnnAngela commented on src/gadgets/libOOUIDialog/MediaWiki:Gadget-libOOUIDialog.js
> +                if (required && !result) {
改为用 [`getValidity`](https://doc.wikimedia.org/oojs-ui/master/js/#!/api/OO.ui.TextInputWidget-method-getValidity) 了

2022-09-11 12:29 UTC, leranjun requested changes

2022-09-11 12:29 UTC, leranjun commented on src/gadgets/libOOUIDialog/MediaWiki:Gadget-libOOUIDialog.js
> +                base.textInput.setValidation(option.validate || "not-empty");
我感觉逻辑应该是 无论是否required都以option指定的为主 然后再fallback检查required的状态

去掉L24的判断，把L25和L26放出来
```js
base.textInput.setIndicator(option.indicator || (option.required ? "required" : null));
base.textInput.setValidation(option.validate || (option.required ? "not-empty" : null));
```

没跑lint 不知道括号是不是多余（

2022-09-11 12:29 UTC, leranjun commented on src/gadgets/libOOUIDialog/MediaWiki:Gadget-libOOUIDialog.js
> +                    await OO.ui.alert($("<p>").html("您没有在刚才的输入框内填写符合要求的信息，请重新填写！"), $.extend({}, option, base, {
框本身应该会变红 我感觉不需要再弹出提示了？

2022-09-11 12:30 UTC, AnnAngela commented on src/gadgets/libOOUIDialog/MediaWiki:Gadget-libOOUIDialog.js
> +                    await OO.ui.alert($("<p>").html("您没有在刚才的输入框内填写符合要求的信息，请重新填写！"), $.extend({}, option, base, {
变红并不能阻止用户按确认键吧

2022-09-11 12:34 UTC, leranjun commented on src/gadgets/libOOUIDialog/MediaWiki:Gadget-libOOUIDialog.js
> +                    await OO.ui.alert($("<p>").html("您没有在刚才的输入框内填写符合要求的信息，请重新填写！"), $.extend({}, option, base, {
只要在外面的循环里没有break掉应该就可以 因为还没return输入的值 目标程序没法进行下一步操作吧

2022-09-11 12:35 UTC, AnnAngela commented on src/gadgets/libOOUIDialog/MediaWiki:Gadget-libOOUIDialog.js
> +                    await OO.ui.alert($("<p>").html("您没有在刚才的输入框内填写符合要求的信息，请重新填写！"), $.extend({}, option, base, {
我先试试看能不能点确定键

2022-09-11 12:57 UTC, leranjun commented on src/gadgets/libOOUIDialog/MediaWiki:Gadget-libOOUIDialog.js
> +                base.textInput.setValidation(option.validate || "not-empty");
看戳了（

2022-09-11 12:58 UTC, AnnAngela commented on src/gadgets/libOOUIDialog/MediaWiki:Gadget-libOOUIDialog.js
> +                    await OO.ui.alert($("<p>").html("您没有在刚才的输入框内填写符合要求的信息，请重新填写！"), $.extend({}, option, base, {
证实了，即使设置了 `validate`，框会变红，但还是能点OK
顺带一提，不知为何 `indicator` 无效，不会出星号

2022-09-11 12:59 UTC, leranjun commented on src/gadgets/libOOUIDialog/MediaWiki:Gadget-libOOUIDialog.js
> +                    await OO.ui.alert($("<p>").html("您没有在刚才的输入框内填写符合要求的信息，请重新填写！"), $.extend({}, option, base, {
我记得1.31确实有一些东西不支持，我忘了是indicator还是某个label配置还是什么

那就这样吧

2022-09-11 12:59 UTC, leranjun approved these changes
LGTM 辛苦了 让小鱼再看看

2022-09-11 20:26 UTC, Dragon-Fish reviewed
LGTM

2022-09-11 20:26 UTC, Dragon-Fish commented on src/gadgets/libOOUIDialog/MediaWiki:Gadget-libOOUIDialog.js
> +            while (Number.MAX_SAFE_INTEGER > Number.MIN_SAFE_INTEGER) {
吐槽一下，这是什么奇技淫巧，这样写是否有特殊的目的？

2022-09-12 00:31 UTC, AnnAngela commented on src/gadgets/libOOUIDialog/MediaWiki:Gadget-libOOUIDialog.js
> +            while (Number.MAX_SAFE_INTEGER > Number.MIN_SAFE_INTEGER) {
避免 eslint 抱怨无限循环

2022-09-12 00:32 UTC, merged