修复和信息栏2.0的兼容问题
MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes pull request #99
Opened 2023-02-21 16:09 UTC by BearBin1215

信息栏2.0后面的{{tabs}}使用AutoWidth=yes会清除浮动（Special:固定链接/6690073），不用则会出现多余白底盖住信息栏。此法解决前后效果差见Special:diff/6690115。

2023-02-21 16:12 UTC, lovelyCARDINAL commented
建议先在[此页面](https://github.com/MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes/blob/master/.mailmap)添加萌娘百科用户名
<!-- BOT-MESSAGE-FOOTER -->
---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

2023-02-21 16:17 UTC, BearBin1215 commented
> 建议先在[此页面](https://github.com/MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes/blob/master/.mailmap)添加萌娘百科用户名
> 
> Generated by [koishi-plugin-github](https://github.koishi.chat/).

这样？

2023-02-21 16:21 UTC, lovelyCARDINAL approved these changes

2023-02-22 02:27 UTC, AnnAngela requested changes
感谢贡献，有点小小的建议~

2023-02-22 02:27 UTC, AnnAngela commented on src/gadgets/site-styles/MediaWiki:Gadget-site-styles.css
> +    display: table-cell;
建议另起一段，在 `table` 下的 `.Tabs.AutoWidth` 才设置 `display: table-cell;`

2023-02-22 02:43 UTC, BearBin1215 commented on src/gadgets/site-styles/MediaWiki:Gadget-site-styles.css
> +    display: table-cell;
这个不是用在table里面的，是同级元素宽度上的问题，见Special:diff/6690115

2023-02-22 03:17 UTC, AnnAngela approved these changes
LGTM

2023-02-22 03:17 UTC, merged